### ISSUE TITLE
Live edit sidebar is nonexistent

### ISSUE THREAD

**Issue by ghost** [InstantUpdate/CMS#6] opened 2015-02-03 20:58 UTC
For some reason, I'm not getting the sidebar with the edit controls. I followed all the documentation. Is there something I'm missing?

**Comment by avramovic** [comment] 2015-02-03 21:03
Are you logged in? Sidebar is displayed only to logged in users.

You can open `yourwebsite.com/index.php/administration/dashboard` to check if you're logged in. If you are not, login screen will appear instead of the Dashboard.

**Comment by CaptSaltyJack** [comment] 2015-02-03 21:03
Yes, definitely logged in. Do I have to have anything special on my HTML page?

**Comment by avramovic** [comment] 2015-02-03 21:10
Well, in most cases no. Does it appear if you open your page like this `yourwebsite.com/index.php/page.html`? Can you leave URL to that page here (if public) so I can take a look?

**Comment by CaptSaltyJack** [comment] 2015-02-03 21:17
Sure. http://test.ff-formula.com/index.php/magic.html

It's very confusing. I also have two DIVs on this page, yet in the page editor, it detects no editable regions.

**Comment by CaptSaltyJack** [comment] 2015-02-03 22:03
It worked for one second! But then I reloaded the page and it went away. And I have this error in the web console:

    ReferenceError: IU_USER_PERMISSIONS is not defined

**Comment by avramovic** [comment] 2015-02-03 22:23
It seems mod_pagespeed is enabled on the server and is messing up with the included JS URLs. I can't test it further without login information so if you want you can create one user for me and send me login details at `avramyu at gmail dot com` so I can check.

The problem is IU will load separate user JS file(s) if user is logged in, so I can't see if it is loading it while I'm logged out.

**Comment by Webinsane** [comment] 2015-02-03 22:31
We prefer using our community to resolve problems. Plus it is easier to send information from our private message system.

http://my.instant-update.com/

Thanks!

**Comment by avramovic** [comment] 2015-02-03 22:59
I agree, there are more options on our forums, however **code errors** should be reported here (and linked to forums if possible).

Anyway, I received your e-mail and logged in and now I can confirm that "user" JS is not being loaded, though the IU is loaded and has marked page as editable. Most likely it is already mentioned `mod_pagespeed` or some other server tool that is caching the output HTML so once cached (while logged out) it'll serve same HTML to all other users until it expires without even letting IU process the page (even if you are logged in, it simply returns cached content before PHP is executed). That one case when it worked is probably when the cache expired so it allowed IU to regenerate HTML.

Please try to disable mod_pagespeed or any other server caching tool, as IU has it's own options to cache pages and display them to logged out users only (so they load faster).

**Comment by CaptSaltyJack** [comment] 2015-02-03 23:31
How did you determine mod_pagespeed is enabled, BTW? I'll see if I can somehow disable it.

**Comment by veb** [comment] 2015-02-04 00:29
If you do a phpinfo page it'll tell you what mods apache is running etc.

```
<?php
phpinfo();
?>
```

**Comment by CaptSaltyJack** [comment] 2015-02-04 00:30
Exactly, and mod_pagespeed is not installed.

**Comment by veb** [comment] 2015-02-04 00:31
He's talking about that OR any other kind of caching your server might have. Do you have anything running that may be? Are you currently using the htaccess-example as .htaccess? (try removing it for a bit)

**Comment by CaptSaltyJack** [comment] 2015-02-04 00:33
I don't see any other caching mods or plugins. Hmm. And removing .htaccess made no difference.

**Comment by veb** [comment] 2015-02-04 00:35
Make a new page. Trial and error :dart:

**Comment by avramovic** [comment] 2015-02-04 01:02
Well, when looking at the source code of your page (when logged in) I can see this:

    <script src="http://test.ff-formula.com/iu-dynamic-js,_init.js+scripts,_vendor,_fbe20327.modernizr.js.pagespeed.jc.n_tUUnpNlJ.js"></script><script>eval(mod_pagespeed_J7XLKdgE7P);</script>

I don't know what is modifying this but it should include these files separately, like this:

    <script src="http://test.ff-formula.com/iu-dynamic-js/init.js" type="text/javascript"></script>

Also that line (first code block) reveals mod_pagespeed JS variable so I assumed it is using mod_pagespeed.

Down below you can see this:

    <script src="http://test.ff-formula.com/iu-resources/min/,qg=base-js.pagespeed.jm.y4ibhr3D7w.js" type="text/javascript"></script>

Once again, this should load like this:

    <script src="http://test.ff-formula.com/iu-resources/min/?g=base-js" type="text/javascript"></script>

...and when logged in it should load `http://test.ff-formula.com/iu-resources/min/?g=user-js` additionally.

You must find out what is modifying your HTML code and disable it. Do you maybe have CloudFlare or similar service enabled which may cache the pages?

**Comment by veb** [comment] 2015-02-04 01:31
Is it the JS minify stuff or tidy HTML that's not working correctly with his bootstrap?

**Comment by CaptSaltyJack** [comment] 2015-02-04 02:12
Strange! I'm not sure what's doing that. I'll investigate. Thanks, guys.

**Comment by avramovic** [comment] 2015-02-04 09:48
I don't think it's (IU's) minify/tidy what's making this problem.

As you can see these two load fine:
http://test.ff-formula.com/iu-resources/min/?g=base-js
http://test.ff-formula.com/iu-resources/min/?g=user-js

However they are not embedded in the page correctly. Something is modifying your HTML in a way it shouldn't (at least not for IU to work correctly).

**Comment by veb** [comment] 2015-02-04 20:23
Would it be a dumb suggestion to try cloning IU into a new directory and using a basic HTML/CSS template to see if it works?

**Comment by CaptSaltyJack** [comment] 2015-02-04 21:15
I plan on wiping the DB and site and starting 100% from scratch. I'll have some time for this next week and I'll report back here.

**Comment by avramovic** [comment] 2015-02-12 14:12
Well, you can try that and let us know of the results, but I still think it's something outside of IU which is modifying your HTML.

**Comment by veb** [comment] 2015-02-12 20:08
Yeah, what ended up happening? I actually tried to replicate this even with
mod pagespeed and bunch of other crap and nope. Didn't get anything. Fresh
install may be what you need.

On Fri, Feb 13, 2015 at 3:12 AM, Nemanja Avramović <notifications@github.com
> wrote:

> Well, you can try that and let us know of the results, but I still think
> it's something outside of IU which is modifying your HTML.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/InstantUpdate/CMS/issues/6#issuecomment-74076394>.
>



-- 

Mike Mackenzie, *BInfoTech*
Manager and Software Developer at veb

http://veb.co.nz
Dunedin, New Zealand

**Comment by Webinsane** [comment] 2015-02-13 17:33
I am sorry for disturbance, but we will be closing issues on GitHub (probably next week). Please use our community if you have any suggestions, features, bugs etc. We also have GitHub registration enabled for easy signup. Our community software (Discourse) tracks any git code directly through the posts.

http://my.instant-update.com/

Thank you for your kind cooperation.

**Comment by CaptSaltyJack** [comment] 2015-02-14 00:00
Sorry guys, been swamped, haven't had a chance to revisit. I think I also may have done one of the steps out of order.. because the documentation was a bit unclear. It says to install a certain way, then it later mentions there's another step (I forget now what it was) that had to be done.

I'll give it a shot when I get some free time.

Also, quick question (before this thread is shut down) :) Is it possible with InstantUpdate to have header and footer in their own files, and to have the other files include those? Or should I just do that using `<?php require(...) ?>`

**Comment by avramovic** [comment] 2015-02-14 10:30
Instant Update can process (simple) PHP so using `include/require` should work.

**Closed** 2015-10-14 19:25 UTC
